name: Teste de CI com Playwright

on: push    # Execute este fluxo de trabalho sempre que um novo commit for enviado ou pull request for aberto.

jobs:
    playwright-run:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'

            - name: Install dependencies
              run: npm install

            - name: Run Playwright tests
              uses: microsoft/playwright-github-action@v1

            - name: Upload Playwright screenshots
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: playwright-screenshots
                path: playwright/screenshots
                if-no-files-found: ignore

            - name: Upload Playwright videos
              uses: actions/upload-artifact@v4
              with:
                name: playwright-videos
                path: playwright/videos
                if-no-files-found: ignore