name: Playwright Tests

on: [push, pull_request]

jobs:
  Playwright-run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run Playwright tests
      run: npx playwright test